SELECT * FROM DEPT
SELECT * FROM EMP
SELECT * FROM SALGRADE


--Q1--
SELECT EMP.EMPNO AS EMP_NUMBER, EMP.ENAME AS FULL_NAME, EMP.SAL AS Salary, DEPT.DEPTNO AS DEPT_ID,DEPT.LOC AS Location
	FROM DEPT JOIN EMP
	ON DEPT.DEPTNO = EMP.DEPTNO

--Q2--
SELECT COUNT(EMPNO) AS NO_OF_EMP,DEPT.LOC AS LOCATION FROM EMP JOIN DEPT
	ON DEPT.DEPTNO=EMP.DEPTNO
	GROUP BY LOC

--Q3--
SELECT DEPT.* FROM DEPT INNER JOIN EMP
	ON DEPT.DEPTNO=EMP.DEPTNO
	WHERE EMP.SAL=(SELECT MAX(SAL) FROM EMP)

--Q4--
SELECT DEPT.*, AVG1.AVERAGE FROM DEPT JOIN 
	(SELECT DEPTNO, AVG(SAL) AS AVERAGE FROM EMP GROUP BY DEPTNO) AS AVG1 ON DEPT.DEPTNO = AVG1.DEPTNO;