
SELECT * FROM DEPT
SELECT * FROM EMP

--Q1--
SELECT DNAME,COUNT(EMP.EMPNO) FROM EMP JOIN DEPT
	ON DEPT.DEPTNO=EMP.DEPTNO
	WHERE (EMP.SAL>2000)
	GROUP BY DEPT.DNAME

--Q2--
SELECT DEPT.* FROM EMP JOIN DEPT
	ON DEPT.DEPTNO=EMP.DEPTNO
	WHERE EMP.SAL=(SELECT MAX(SAL) FROM EMP)


--Q3--
SELECT TOP 1 DEPT.*, AVG1.AVERAGE FROM DEPT JOIN 
	(SELECT DEPTNO, AVG(SAL) AS AVERAGE FROM EMP GROUP BY DEPTNO) AS AVG1 
		ON DEPT.DEPTNO = AVG1.DEPTNO ORDER BY AVG1.AVERAGE ASC
		
--Q4--
CREATE TABLE USERS
	(ID INT NOT NULL PRIMARY KEY CHECK(ID<=9999),
	UNAME VARCHAR(9) NOT NULL,
	USERN VARCHAR(20) NOT NULL,
	DOB TIMESTAMP);

--Q5--
CREATE TABLE POSTS
	(ID INT NOT NULL PRIMARY KEY CHECK(ID>0),
	DESCRIPTION VARCHAR NOT NULL,
	DATETIME TIMESTAMP,
	USERID INT FOREIGN KEY REFERENCES USERS(ID));


