
--(Q1)--
SELECT * FROM EMP WHERE 
	SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY (DEPTNO)) OR SAL IN (SELECT MIN(SAL) FROM EMP GROUP BY (DEPTNO)) ORDER BY DEPTNO;

--(Q2)--

SELECT EMP.ENAME, EMP.EMPNO, DEPT.DEPTNO FROM DEPT,EMP
	WHERE (EMP.DEPTNO > 20 and EMP.DEPTNO = DEPT.DEPTNO AND DEPT.DNAME LIKE '%A%');
SELECT ENAME,EMPNO, DEPTNO FROM EMP
	WHERE (DEPTNO > 20 AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME LIKE '%A%'));


SELECT * FROM EMP WHERE
	(2*SAL < (SELECT SAL FROM EMP WHERE JOB IN ('PRESIDENT')));


SELECT * FROM EMP WHERE 
	(EMPNO NOT IN (SELECT MGR FROM EMP WHERE MGR IS NOT NULL))


SELECT CONCAT(ENAME ,' is ',JOB) AS INTRO FROM EMP
